# Generated by Django 3.1.4 on 2020-12-06 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_auto_20201207_0304'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='taskname',
            new_name='title',
        ),
    ]
